language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
before_script:
  - npm install
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: fossasia:2bIMMtLKJpk9qCKUJTZVF2KD
